"""
ShadowMerchant — Reddit PRAW Poster
=====================================
Submits the deal draft (generated by growth_orchestrator) to Reddit.

IMPORTANT: Run this ONLY after:
  1. Your Reddit account is 2+ weeks old
  2. You have 100+ comment karma (earned genuinely)
  3. You've reviewed the draft sent to your admin Telegram

Usage:
    python scripts/growth/reddit_poster.py --draft   # show today's draft only
    python scripts/growth/reddit_poster.py --submit  # submit to Reddit (human-triggered)
"""

import os
import sys
import json
import time
import random
import io
from pathlib import Path
from datetime import datetime, timezone, timedelta

if sys.platform == "win32":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding="utf-8", errors="replace")

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
from dotenv import load_dotenv
load_dotenv(dotenv_path=ROOT / ".env")

import logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger("reddit")

# ── Config ────────────────────────────────────────────────────
REDDIT_CLIENT_ID     = os.getenv("REDDIT_CLIENT_ID", "")
REDDIT_CLIENT_SECRET = os.getenv("REDDIT_CLIENT_SECRET", "")
REDDIT_USERNAME      = os.getenv("REDDIT_USERNAME", "")
REDDIT_PASSWORD      = os.getenv("REDDIT_PASSWORD", "")

# State file tracks last submission times per subreddit
STATE_FILE = Path(__file__).parent / ".reddit_state.json"

# Subreddit rotation — post to different ones across the week
SUBREDDIT_SCHEDULE = {
    0: "frugal_india",         # Monday
    1: "frugal_india",         # Tuesday
    2: "india",                # Wednesday
    3: "frugal_india",         # Thursday
    4: "onlineshopping",       # Friday
    5: "frugal_india",         # Saturday
    6: None,                   # Sunday — no Reddit on Sundays (rest day)
}

# Rules per subreddit
SUBREDDIT_RULES = {
    "frugal_india": {
        "allow_links": True,
        "require_flair": False,
        "notes": "Friendly to deal posts. Use [Amazon] [Flipkart] prefix in title.",
    },
    "india": {
        "allow_links": False,   # text posts only to avoid spam filter
        "require_flair": True,
        "flair": "AskIndia",
        "notes": "Use text post format. Don't post raw affiliate links.",
    },
    "onlineshopping": {
        "allow_links": True,
        "require_flair": False,
        "notes": "Deal posts allowed. Keep it factual.",
    },
    "personalfinanceindia": {
        "allow_links": False,
        "require_flair": False,
        "notes": "Frame as 'how I saved money' not as a deal post.",
    },
    "IndianGaming": {
        "allow_links": True,
        "require_flair": False,
        "notes": "Gaming deals only — don't post irrelevant categories here.",
    },
}


def load_state() -> dict:
    if STATE_FILE.exists():
        try:
            return json.loads(STATE_FILE.read_text())
        except Exception:
            pass
    return {"posts": [], "last_post_time": None}


def save_state(state: dict):
    STATE_FILE.write_text(json.dumps(state, indent=2, default=str))


def can_post_today(state: dict, subreddit: str) -> tuple[bool, str]:
    """Check if we can post today (max 2 posts/week per subreddit)."""
    posts = state.get("posts", [])
    cutoff = datetime.now(timezone.utc) - timedelta(days=7)

    # Posts to this subreddit in the last 7 days
    recent = [
        p for p in posts
        if p.get("subreddit") == subreddit
        and datetime.fromisoformat(p["time"]) > cutoff
    ]

    if len(recent) >= 2:
        return False, f"Already posted {len(recent)} times to r/{subreddit} this week. Max is 2."

    # Global cooldown: min 20 hours between any posts
    last_time_str = state.get("last_post_time")
    if last_time_str:
        last_time = datetime.fromisoformat(last_time_str)
        if last_time.tzinfo is None:
            last_time = last_time.replace(tzinfo=timezone.utc)
        hours_since = (datetime.now(timezone.utc) - last_time).total_seconds() / 3600
        if hours_since < 20:
            return False, f"Last post was {hours_since:.1f}h ago. Wait {20 - hours_since:.1f}h more."

    return True, "OK"


def get_today_deal() -> dict | None:
    """Get the best deal from MongoDB for today's Reddit post."""
    try:
        from utils.db import get_db
        db = get_db()
        cutoff = datetime.now(timezone.utc) - timedelta(hours=12)
        return db.deals.find_one(
            {"is_active": True, "deal_score": {"$gte": 65}, "scraped_at": {"$gte": cutoff}},
            sort=[("deal_score", -1)]
        )
    except Exception as e:
        log.error(f"DB query failed: {e}")
        return None


def build_post(deal: dict, subreddit: str) -> dict:
    """Build a Reddit-ready post dict."""
    title_raw = deal.get("title", "")[:75]
    cur       = deal.get("discounted_price") or deal.get("current_price", 0)
    orig      = deal.get("original_price", 0)
    disc      = deal.get("discount_percent", 0)
    score     = deal.get("deal_score", 0)
    platform  = deal.get("source_platform", "Amazon").title()
    aff_url   = deal.get("affiliate_url") or deal.get("product_url", "")
    category  = deal.get("category", "general")

    rules = SUBREDDIT_RULES.get(subreddit, {})
    allow_links = rules.get("allow_links", True)

    # Title format
    title = f"[{platform}] {title_raw} — INR {cur:,.0f} ({disc}% off, 30-day low verified)"

    # Body — text format (works for both text and link posts)
    body = (
        f"**Price history check:**\n\n"
        f"| Field | Value |\n"
        f"|---|---|\n"
        f"| Current price | INR {cur:,.0f} |\n"
        f"| Listed 'original' | INR {orig:,.0f} |\n"
        f"| 30-day verified low | INR {cur:,.0f} |\n"
        f"| Shadow Score | {score}/100 |\n\n"
        f"This is a genuine discount — checked against 30-day price history. "
        f"The original price is real, not an inflated anchor.\n\n"
    )

    if allow_links:
        body += f"**Direct link:** {aff_url} *(affiliate — I earn a small commission if you buy)*\n\n"

    body += (
        f"---\n"
        f"*I cross-check every deal against 30-day price data before posting. "
        f"Most Amazon 'sales' use inflated anchor prices — this one passed the check.*"
    )

    # Text-only variant for subreddits that don't allow links
    text_only_body = (
        f"Found a deal worth sharing on r/{subreddit}:\n\n"
        f"**{title_raw}** from {platform}\n\n"
        f"Current: INR {cur:,.0f} | Original listed: INR {orig:,.0f} | {disc}% off\n\n"
        f"Checked against 30-day price history — this is the genuine 30-day low. "
        f"Shadow Score: {score}/100.\n\n"
        f"Search for it on {platform} or DM me for the direct link.\n\n"
        f"---\n"
        f"*Tracking deals with price history to filter out fake sales.*"
    )

    return {
        "subreddit":  subreddit,
        "title":      title,
        "body":       body if allow_links else text_only_body,
        "url":        aff_url if allow_links else None,
        "is_link":    allow_links,
        "rules_note": rules.get("notes", ""),
        "deal_title": title_raw,
        "score":      score,
    }


def show_draft(post: dict):
    """Print the draft for human review."""
    print("\n" + "="*60)
    print(f"REDDIT DRAFT — r/{post['subreddit']}")
    print("="*60)
    print(f"\nTITLE:\n{post['title']}\n")
    print(f"BODY:\n{post['body']}\n")
    if post.get("url"):
        print(f"LINK URL: {post['url']}\n")
    print(f"RULES NOTE: {post['rules_note']}")
    print("="*60)
    print("\nTo submit: run with --submit flag")
    print("To submit manually: reddit.com/r/{}/submit\n".format(post["subreddit"]))


def submit_post(post: dict, state: dict) -> bool:
    """Submit post to Reddit via PRAW."""
    if not all([REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET, REDDIT_USERNAME, REDDIT_PASSWORD]):
        log.error(
            "Reddit credentials not set in .env\n"
            "Required: REDDIT_CLIENT_ID, REDDIT_CLIENT_SECRET, REDDIT_USERNAME, REDDIT_PASSWORD"
        )
        return False

    try:
        import praw
    except ImportError:
        log.error("praw not installed: pip install praw")
        return False

    reddit = praw.Reddit(
        client_id=REDDIT_CLIENT_ID,
        client_secret=REDDIT_CLIENT_SECRET,
        username=REDDIT_USERNAME,
        password=REDDIT_PASSWORD,
        user_agent=f"ShadowMerchant:deal_poster:v1.0 (by /u/{REDDIT_USERNAME})",
    )

    # Verify auth
    try:
        me = reddit.user.me()
        log.info(f"Logged in as: u/{me.name} | Karma: {me.link_karma} link / {me.comment_karma} comment")

        if me.comment_karma < 50:
            log.warning(
                f"Comment karma is only {me.comment_karma}. "
                "You need 100+ karma before posting deals. "
                "Build karma first by commenting genuinely in subreddits."
            )
            confirm = input("Karma is low. Post anyway? (y/N): ").strip().lower()
            if confirm != "y":
                return False

    except Exception as e:
        log.error(f"Reddit auth failed: {e}")
        return False

    sub = reddit.subreddit(post["subreddit"])

    # Random delay (looks human)
    delay = random.uniform(3, 8)
    log.info(f"Waiting {delay:.1f}s before posting...")
    time.sleep(delay)

    try:
        if post["is_link"] and post.get("url"):
            submission = sub.submit(title=post["title"], url=post["url"])
        else:
            submission = sub.submit(title=post["title"], selftext=post["body"])

        post_url = f"https://reddit.com{submission.permalink}"
        log.info(f"Posted successfully: {post_url}")

        # Update state
        state.setdefault("posts", []).append({
            "subreddit": post["subreddit"],
            "title":     post["deal_title"],
            "url":       post_url,
            "time":      datetime.now(timezone.utc).isoformat(),
        })
        state["last_post_time"] = datetime.now(timezone.utc).isoformat()
        save_state(state)

        print(f"\nPosted: {post_url}\n")
        return True

    except Exception as e:
        log.error(f"Reddit submission failed: {e}")
        if "RATELIMIT" in str(e).upper():
            log.error("Rate limited by Reddit. Wait 10 minutes before retrying.")
        elif "SUBREDDIT_NOTALLOWED" in str(e).upper():
            log.error(f"r/{post['subreddit']} doesn't allow link posts. Switch to text post mode.")
        return False


def main():
    import argparse
    parser = argparse.ArgumentParser(description="ShadowMerchant Reddit Poster")
    parser.add_argument("--draft",   action="store_true", help="Show today's draft without submitting")
    parser.add_argument("--submit",  action="store_true", help="Submit draft to Reddit")
    parser.add_argument("--sub",     default=None,        help="Override subreddit (e.g. frugal_india)")
    args = parser.parse_args()

    today_idx  = datetime.now().weekday()
    subreddit  = args.sub or SUBREDDIT_SCHEDULE.get(today_idx)

    if not subreddit:
        print("No Reddit posting scheduled for today (Sunday = rest day). Use --sub to override.")
        return

    state = load_state()

    # Safety check
    ok, reason = can_post_today(state, subreddit)
    if not ok:
        print(f"BLOCKED: {reason}")
        return

    deal = get_today_deal()
    if not deal:
        print("No suitable deal found today (need score >= 65, scraped in last 12h)")
        print("Check if the scraper ran today: python scripts/scheduler.py --run-now")
        return

    post = build_post(deal, subreddit)

    if args.draft or not args.submit:
        show_draft(post)

    if args.submit:
        print(f"\nAbout to post to r/{subreddit}:")
        print(f"Title: {post['title'][:80]}")
        confirm = input("\nConfirm submit? (y/N): ").strip().lower()
        if confirm == "y":
            submit_post(post, state)
        else:
            print("Cancelled.")


if __name__ == "__main__":
    main()
