"""
ShadowMerchant Pipeline Entry Point
Reads scraper_targets.json (generated by trend_analyzer.py) and runs
the top-priority scrapers, processes deals, and writes to MongoDB.

Usage:
    python run_pipeline.py                  # Use trend targets if available
    python run_pipeline.py --scrapers amazon flipkart myntra
    python run_pipeline.py --all            # Run all scrapers
"""
import os
import sys
import json
import uuid
import logging
import argparse
import requests
import pymongo
from datetime import datetime, timezone
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, str(Path(__file__).parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("pipeline")


# ═══════════════════════════════════════════════════════════
# SCRAPE LOG — writes a structured record to MongoDB after
# each scraper run so we can track health over time.
# ═══════════════════════════════════════════════════════════

def log_scraper_run(
    db,
    platform: str,
    deals_found: int,
    deals_saved: int,
    errors: list,
    elapsed_seconds: int = 0,
) -> str | None:
    """Write a structured run record to MongoDB scrapelogs after each scraper finishes.
    Returns the inserted document's _id (str) so the caller can back-fill deals_saved.
    """
    try:
        result = db.scrapelogs.insert_one({
            "platform":        platform,
            "run_at":          datetime.now(timezone.utc),
            "deals_found":     deals_found,
            "deals_saved":     deals_saved,
            "elapsed_seconds": elapsed_seconds,
            "errors":          errors[:10],  # cap at 10 entries
            "status":          "success" if not errors else ("failure" if deals_found == 0 else "partial"),
        })
        # Ensure index exists (safe to call repeatedly):
        db.scrapelogs.create_index(
            [("platform", pymongo.ASCENDING), ("run_at", pymongo.DESCENDING)],
            background=True
        )
        return str(result.inserted_id)
    except Exception as e:
        logger.warning(f"[ScrapeLog] Failed to write log for {platform}: {e}")
        return None


def update_scrape_log_saved(db, log_id: str, deals_saved: int) -> None:
    """Back-fill the deals_saved count after process_and_save() completes."""
    if not log_id:
        return
    try:
        import bson
        db.scrapelogs.update_one(
            {"_id": bson.ObjectId(log_id)},
            {"$set": {"deals_saved": deals_saved}}
        )
    except Exception as e:
        logger.debug(f"[ScrapeLog] Could not back-fill deals_saved for {log_id}: {e}")


def check_and_alert_zero_deals(db, platform: str, notify_fn=None):
    """
    Alert if a scraper has returned 0 deals for 3 consecutive runs.
    Pass notify_fn=send_telegram_alert (or similar) to fire the alert.
    """
    try:
        recent = list(db.scrapelogs.find(
            {"platform": platform},
            sort=[("run_at", pymongo.DESCENDING)],
            limit=3
        ))
        if len(recent) == 3 and all(r.get("deals_found", 0) == 0 for r in recent):
            msg = (
                f"⚠️ [{platform.upper()}] 0 deals for 3 consecutive runs — "
                "scraper may be broken"
            )
            logger.critical(msg)
            if notify_fn:
                notify_fn(msg)
    except Exception as e:
        logger.warning(f"[ScrapeLog] Zero-deal alert check failed for {platform}: {e}")


# ═══════════════════════════════════════════════════════════
# CACHE REFRESH — flushes Redis deal cache and revalidates
# ISR pages after each pipeline run.
# ═══════════════════════════════════════════════════════════

def trigger_cache_refresh():
    """
    Calls the Vercel cron endpoint to flush Redis deal cache and revalidate ISR pages.
    Uses GET + Authorization: Bearer CRON_SECRET
    (matches apps/web/src/app/api/cron/refresh-deals/route.ts).
    Fails silently — a cache miss is recoverable, a broken pipeline run is not.
    """
    cron_secret = os.getenv("CRON_SECRET")
    app_url     = os.getenv("NEXT_PUBLIC_APP_URL", "https://www.shadowmerchant.online")

    if not cron_secret:
        logger.warning(
            "[Cache] CRON_SECRET not in .env — skipping cache refresh. "
            "Users will see stale deals for up to 30 minutes."
        )
        return

    try:
        r = requests.get(
            f"{app_url}/api/cron/refresh-deals",
            headers={"Authorization": f"Bearer {cron_secret}"},
            timeout=15
        )
        stale = r.json().get("stale_deactivated", "?") if r.headers.get("content-type", "").startswith("application/json") else "?"
        logger.info(
            f"[Cache] Refresh triggered — HTTP {r.status_code} — "
            f"{stale} stale deals deactivated"
        )
    except Exception as e:
        logger.warning(f"[Cache] Refresh failed (non-fatal): {e}")


# ── Canonical category taxonomy (must match CategoryBrowser.tsx) ──────────
# Maps raw scraped strings → canonical slugs. Case-insensitive prefix matching.
CATEGORY_MAP: dict[str, str] = {
    # Electronics
    "electronic": "electronics", "mobile": "electronics", "laptop": "electronics",
    "computer": "electronics", "tablet": "electronics", "camera": "electronics",
    "headphone": "electronics", "earphone": "electronics", "television": "electronics",
    "tv": "electronics", "gadget": "electronics", "wearable": "electronics",
    "smartwatch": "electronics", "speaker": "electronics", "gaming": "gaming",
    "console": "gaming", "game": "gaming",
    # Fashion
    "fashion": "fashion", "clothing": "fashion", "apparel": "fashion",
    "shirt": "fashion", "trouser": "fashion", "dress": "fashion",
    "jeans": "fashion", "kurta": "fashion", "saree": "fashion",
    "women": "fashion", "men": "fashion", "ethnic": "fashion",
    "footwear": "fashion", "shoe": "fashion", "sandal": "fashion", "slipper": "fashion",
    "bag": "fashion", "handbag": "fashion", "wallet": "fashion", "accessory": "fashion",
    # Beauty & Health
    "beauty": "beauty", "skincare": "beauty", "makeup": "beauty",
    "cosmetic": "beauty", "hair": "beauty", "fragrance": "beauty",
    "grooming": "beauty", "health": "health", "nutrition": "health",
    "supplement": "health", "fitness": "sports", "sport": "sports",
    "gym": "sports", "yoga": "sports", "exercise": "sports",
    # Home
    "home": "home", "kitchen": "home", "furniture": "home",
    "decor": "home", "bedding": "home", "appliance": "home",
    "cleaning": "home", "tool": "home", "garden": "home",
    # Books
    "book": "books", "stationery": "books", "office": "books",
    # Toys
    "toy": "toys", "baby": "toys", "kids": "toys", "children": "toys",
    # Automotive
    "auto": "automotive", "car": "automotive", "bike": "automotive",
    "vehicle": "automotive",
    # Grocery
    "grocery": "grocery", "food": "grocery", "snack": "grocery",
    "beverage": "grocery", "organic": "grocery",
    # Travel
    "travel": "travel", "luggage": "travel", "suitcase": "travel",
}

CANONICAL_SLUGS = {
    "electronics", "fashion", "beauty", "home", "sports",
    "books", "toys", "health", "automotive", "grocery", "travel", "gaming"
}

def normalize_category(raw: str) -> str:
    """Map a free-form scraped category string to a canonical slug."""
    if not raw:
        return "other"
    lower = raw.lower().strip()
    # Already canonical
    if lower in CANONICAL_SLUGS:
        return lower
    # Keyword prefix match
    for keyword, slug in CATEGORY_MAP.items():
        if keyword in lower:
            return slug
    return "other"


SCRAPER_MAP = {
    "amazon":   ("scrapers.amazon_scraper",   "AmazonScraper"),
    "flipkart": ("scrapers.flipkart_scraper", "FlipkartScraper"),
    "myntra":   ("scrapers.myntra_scraper",   "MyntraScraper"),
    "meesho":   ("scrapers.meesho_scraper",   "MeeshoScraper"),
    "nykaa":    ("scrapers.nykaa_scraper",    "NykaaScraper"),
    "croma":    ("scrapers.croma_scraper",    "CromaScraper"),
}

# Default scrapers to run when no targets file is available
# NOTE: Only list scrapers confirmed working. flipkart=410 Gone, myntra=TLS blocked.
DEFAULT_SCRAPERS = ["amazon", "meesho"]

# Allowed platform domains — only URLs on these domains are saved
ALLOWED_DOMAINS = (
    "amazon.in", "amazon.com",
    "flipkart.com",
    "myntra.com",
    "meesho.com",
    "nykaa.com",
    "croma.com",
    "tatacliq.com",
)


def validate_affiliate_url(url: str, platform: str) -> str | None:
    """
    Validates and normalises an affiliate URL before saving to MongoDB.
    Returns the cleaned URL, or None if the URL is unusable.
    """
    if not url or not isinstance(url, str):
        return None

    url = url.strip()

    # Must be an absolute HTTPS URL
    if not url.startswith("https://") and not url.startswith("http://"):
        logger.debug(f"Rejecting relative/schemeless URL [{platform}]: {url[:80]}")
        return None

    # Must belong to a known platform domain
    if not any(domain in url for domain in ALLOWED_DOMAINS):
        logger.debug(f"Rejecting unknown-domain URL [{platform}]: {url[:80]}")
        return None

    # Flipkart-specific: rebuild a stable product URL from pid if slug URL is present
    # Flipkart stable format: https://www.flipkart.com/product/p/iteme?pid=XXXX
    if platform == "flipkart" and "/p/" in url:
        try:
            from urllib.parse import urlparse, parse_qs, urlencode, urlunparse
            parsed = urlparse(url)
            qs = parse_qs(parsed.query)
            pid = qs.get("pid", [None])[0]
            if pid:
                # Keep existing clean URL — pid is present, URL is stable
                return url
            # No pid → this is a session-scoped slug, mark as unusable
            logger.debug(f"Rejecting Flipkart session-slug URL (no pid): {url[:80]}")
            return None
        except Exception:
            return url  # If parsing fails, give it the benefit of the doubt

    return url


def load_targets() -> list[str]:
    """Load scraper priority from trend_analyzer output if available."""
    targets_file = Path(__file__).parent / "scraper_targets.json"
    if targets_file.exists():
        with open(targets_file) as f:
            targets = json.load(f)
        # Return platforms that have queries assigned, ordered by number of queries
        ordered = sorted(targets.keys(), key=lambda p: len(targets[p]), reverse=True)
        logger.info(f"Loaded trend targets: {ordered}")
        return ordered
    logger.info("No trend targets found — using defaults")
    return DEFAULT_SCRAPERS


def run_scraper(name: str) -> list:
    import importlib
    import time as _time
    if name not in SCRAPER_MAP:
        logger.warning(f"Unknown scraper: {name}")
        return []
    module_path, class_name = SCRAPER_MAP[name]
    sc_start = _time.monotonic()
    try:
        mod = importlib.import_module(module_path)
        cls = getattr(mod, class_name)
        scraper = cls()
        logger.info(f"▶ Running {name} scraper...")
        deals = scraper.scrape_deals()
        elapsed = int(_time.monotonic() - sc_start)
        logger.info(f"  ✅ {name}: {len(deals)} deals")

        # REQ 4: CueLinks affiliate URL conversion for supported platforms
        # Activates automatically when CUELINKS_SID is set in .env
        try:
            from utils.cuelinks import convert_to_affiliate, CUELINKS_PLATFORMS
            if name in CUELINKS_PLATFORMS:
                for deal in deals:
                    raw_url = getattr(deal, 'product_url', None) or (deal.get('product_url') if isinstance(deal, dict) else None)
                    if raw_url:
                        converted = convert_to_affiliate(raw_url, name)
                        if isinstance(deal, dict):
                            deal['product_url'] = converted
                        else:
                            deal.product_url = converted
        except Exception as e:
            logger.debug(f"[CueLinks] Skipped for {name}: {e}")

        # REQ 7: Log this run to MongoDB scrapelogs with elapsed time.
        # deals_saved is 0 here — back-filled by process_and_save() per-scraper.
        # We store the log_id so we can update deals_saved after the save step.
        try:
            _mongo_client = pymongo.MongoClient(os.getenv("MONGODB_URI"), serverSelectionTimeoutMS=5000)
            _db = _mongo_client.shadowmerchant
            log_scraper_run(_db, name, len(deals), 0, [], elapsed)
            check_and_alert_zero_deals(_db, name)
            _mongo_client.close()
        except Exception as e:
            logger.warning(f"[ScrapeLog] Could not write run log for {name}: {e}")

        return deals
    except Exception as e:
        elapsed = int(_time.monotonic() - sc_start)
        logger.error(f"  ❌ {name} scraper failed: {e}")
        # Log failed run too
        try:
            _mongo_client = pymongo.MongoClient(os.getenv("MONGODB_URI"), serverSelectionTimeoutMS=5000)
            log_scraper_run(_mongo_client.shadowmerchant, name, 0, 0, [str(e)], elapsed)
            _mongo_client.close()
        except Exception:
            pass
        return []


def process_and_save(all_deals: list) -> int:
    """De-duplicate, score, and upsert deals into MongoDB."""
    if not all_deals:
        logger.warning("No deals to process")
        return 0
    try:
        import pymongo
        from processors.deal_scorer import score_deal_with_breakdown
        from processors.deduplicator import deduplicate_deals

        client = pymongo.MongoClient(os.getenv("MONGODB_URI"), serverSelectionTimeoutMS=10000)
        db = client.shadowmerchant

        # ── Deduplicate cross-platform duplicates before inserting ──────────
        deduped_deals = deduplicate_deals(all_deals)
        logger.info(f"After deduplication: {len(deduped_deals)}/{len(all_deals)} unique deals")

        saved = 0
        for deal in deduped_deals:
            try:
                # score_deal_with_breakdown returns (score, breakdown_dict)
                deal_score, score_breakdown = score_deal_with_breakdown(deal)

                # Extract fields — works for both RawDeal dataclass and dict
                def _f(field, default=""):
                    if isinstance(deal, dict):
                        return deal.get(field, default)
                    return getattr(deal, field, default)

                title        = str(_f("title", "")).strip()
                platform     = str(_f("platform", _f("source_platform", "unknown")))
                orig_price   = float(_f("original_price", 0) or 0)
                disc_price   = float(_f("discounted_price", 0) or 0)
                discount_pct = _f("discount_percent", None)
                if discount_pct is None:
                    discount_pct = int(round((1 - disc_price / orig_price) * 100)) if orig_price > disc_price > 0 else 0
                product_url  = str(_f("product_url", "") or _f("affiliate_url", "")).strip()
                image_url    = str(_f("image_url", "") or "").strip()
                category     = normalize_category(str(_f("category", "") or ""))
                alternate_links = _f("alternate_links", []) or []

                # ── Validate and normalise the affiliate URL ───────────────────
                product_url = validate_affiliate_url(product_url, platform)

                if not title or disc_price <= 0 or not product_url:
                    logger.debug(f"Skipping deal — invalid data: title={bool(title)} price={disc_price} url={product_url!r:.60}")
                    continue

                # ── is_pro_exclusive: top-tier deals by score AND discount ───────
                # Pro gating: score >= 55 AND discount >= 40% → Pro-exclusive (~10-15% of deals)
                # Threshold calibrated to sigmoid scorer: max realistic score ≈66 for fashion/cosmetics
                is_pro_exclusive = bool(int(deal_score) >= 55 and int(discount_pct) >= 40)

                doc = {
                    "title":            title,
                    "source_platform":  platform,
                    "original_price":   orig_price,
                    "discounted_price": disc_price,
                    "discount_percent": int(discount_pct),
                    "deal_score":       int(deal_score),
                    "score_breakdown":  score_breakdown,
                    "affiliate_url":    product_url,
                    "image_url":        image_url,
                    "category":         category,
                    "brand":            str(_f("brand", "") or ""),
                    "rating":           float(_f("rating", 0) or 0),
                    "rating_count":     int(_f("rating_count", 0) or 0),
                    "alternate_links":  alternate_links,
                    "is_active":        True,
                    "is_pro_exclusive": is_pro_exclusive,
                    "is_trending":      int(deal_score) >= 80,
                    "scraped_at":       datetime.utcnow(),
                    "updated_at":       datetime.utcnow(),
                }

                result = db.deals.update_one(
                    {"affiliate_url": product_url},
                    {
                        "$set": doc,
                        "$push": {
                            "price_history": {
                                "$each": [{"date": datetime.utcnow(), "price": disc_price}],
                                "$slice": -90,  # BUG-01: 30 days at 3 scrapes/day
                            }
                        },
                        "$setOnInsert": {
                            "created_at": datetime.utcnow(),
                            "published_at": datetime.utcnow(),
                            "deal_id": str(uuid.uuid4()),
                        }
                    },
                    upsert=True,
                )
                if result.upserted_id or result.modified_count:
                    saved += 1

            except Exception as e:
                logger.debug(f"Deal save error: {e}")

        # ── Trending flag management ───────────────────────────────────
        # The authoritative trending selection (composite score: absolute savings,
        # discount %, price tier, deal_score, social proof, freshness) lives in
        # scheduler.py → run_pipeline() and runs automatically after each scrape.
        # Do NOT replicate a simplified version here \u2014 it would race-overwrite
        # the composite selection and cause inconsistent trending sets.

        client.close()
        logger.info(f"💾 Saved/updated {saved}/{len(deduped_deals)} deals to MongoDB")
        return saved

    except Exception as e:
        logger.error(f"DB save failed: {e}")
        return 0


def main():
    parser = argparse.ArgumentParser(description="ShadowMerchant Scraper Pipeline")
    parser.add_argument("--scrapers", nargs="+", choices=list(SCRAPER_MAP.keys()), help="Scrapers to run")
    parser.add_argument("--all", action="store_true", help="Run all scrapers")
    parser.add_argument("--no-save", action="store_true", help="Don't save to DB (dry run)")
    args = parser.parse_args()

    if args.all:
        to_run = list(SCRAPER_MAP.keys())
    elif args.scrapers:
        to_run = args.scrapers
    else:
        to_run = load_targets()

    logger.info(f"🚀 Pipeline starting — scrapers: {to_run}")
    start = datetime.utcnow()

    all_deals = []
    for name in to_run:
        deals = run_scraper(name)
        all_deals.extend(deals)

    logger.info(f"📦 Total deals collected: {len(all_deals)}")

    saved = 0
    if not args.no_save:
        saved = process_and_save(all_deals)
    else:
        logger.info("[DRY RUN] Skipping DB save")
        # Print sample
        for d in all_deals[:5]:
            raw = d if isinstance(d, dict) else d.__dict__
            print(f"  {raw.get('title', '')[:60]} | ₹{raw.get('discounted_price', 0)} | {raw.get('discount_percent', 0)}% off")

    elapsed = (datetime.now(timezone.utc).replace(tzinfo=None) - start).seconds
    logger.info(f"✅ Pipeline complete — {saved} deals saved in {elapsed}s")

    # Run Algolia sync so manual pipeline execution stays consistent with the chron scheduler
    if saved > 0 and not args.no_save:
        try:
            import subprocess
            logger.info("🔄 Triggering Algolia synchronization...")
            subprocess.run([sys.executable, "index_algolia.py"],
                cwd=str(Path(__file__).parent), capture_output=True, timeout=120)
            logger.info("✅ Algolia sync complete")
        except Exception as e:
            logger.error(f"❌ Algolia sync failed: {e}")

    # REQ 8: Flush Redis deal cache + revalidate ISR pages
    trigger_cache_refresh()

if __name__ == "__main__":
    main()
