"""
ShadowMerchant Pipeline Entry Point
Reads scraper_targets.json (generated by trend_analyzer.py) and runs
the top-priority scrapers, processes deals, and writes to MongoDB.

Usage:
    python run_pipeline.py                  # Use trend targets if available
    python run_pipeline.py --scrapers amazon flipkart myntra
    python run_pipeline.py --all            # Run all scrapers
"""
import os
import sys
import json
import logging
import argparse
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()
sys.path.insert(0, str(Path(__file__).parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger("pipeline")

SCRAPER_MAP = {
    "amazon":   ("scrapers.amazon_scraper",   "AmazonScraper"),
    "flipkart": ("scrapers.flipkart_scraper", "FlipkartScraper"),
    "myntra":   ("scrapers.myntra_scraper",   "MyntraScraper"),
    "meesho":   ("scrapers.meesho_scraper",   "MeeshoScraper"),
    "nykaa":    ("scrapers.nykaa_scraper",    "NykaaScraper"),
    "croma":    ("scrapers.croma_scraper",    "CromaScraper"),
}

# Default scrapers to run when no targets file is available
DEFAULT_SCRAPERS = ["amazon", "flipkart", "myntra"]


def load_targets() -> list[str]:
    """Load scraper priority from trend_analyzer output if available."""
    targets_file = Path(__file__).parent / "scraper_targets.json"
    if targets_file.exists():
        with open(targets_file) as f:
            targets = json.load(f)
        # Return platforms that have queries assigned, ordered by number of queries
        ordered = sorted(targets.keys(), key=lambda p: len(targets[p]), reverse=True)
        logger.info(f"Loaded trend targets: {ordered}")
        return ordered
    logger.info("No trend targets found — using defaults")
    return DEFAULT_SCRAPERS


def run_scraper(name: str) -> list:
    import importlib
    if name not in SCRAPER_MAP:
        logger.warning(f"Unknown scraper: {name}")
        return []
    module_path, class_name = SCRAPER_MAP[name]
    try:
        mod = importlib.import_module(module_path)
        cls = getattr(mod, class_name)
        scraper = cls()
        logger.info(f"▶ Running {name} scraper...")
        deals = scraper.scrape_deals()
        logger.info(f"  ✅ {name}: {len(deals)} deals")
        return deals
    except Exception as e:
        logger.error(f"  ❌ {name} scraper failed: {e}")
        return []


def process_and_save(all_deals: list) -> int:
    """De-duplicate, score, and upsert deals into MongoDB."""
    if not all_deals:
        logger.warning("No deals to process")
        return 0
    try:
        import pymongo
        from processors.deal_scorer import score_deal

        client = pymongo.MongoClient(os.getenv("MONGO_URI"), serverSelectionTimeoutMS=10000)
        db = client.shadowmerchant

        saved = 0
        for deal in all_deals:
            try:
                # Build document
                raw = deal if isinstance(deal, dict) else deal.__dict__
                title         = str(raw.get("title", "")).strip()
                platform      = raw.get("platform", raw.get("source_platform", "unknown"))
                orig_price    = float(raw.get("original_price", 0) or 0)
                disc_price    = float(raw.get("discounted_price", 0) or 0)
                discount_pct  = raw.get("discount_percent", None)
                if discount_pct is None:
                    discount_pct = int(round((1 - disc_price / orig_price) * 100)) if orig_price > disc_price > 0 else 0
                product_url   = str(raw.get("product_url", raw.get("affiliate_url", ""))).strip()
                image_url     = str(raw.get("image_url", "")).strip()
                category      = raw.get("category", "other")

                if not title or disc_price <= 0 or not product_url:
                    continue

                # Score
                try:
                    deal_score = score_deal({
                        "discount_percent": discount_pct,
                        "discounted_price": disc_price,
                        "original_price": orig_price,
                        "category": category,
                    })
                except Exception:
                    deal_score = min(discount_pct, 100)

                doc = {
                    "title":            title,
                    "platform":         platform,
                    "original_price":   orig_price,
                    "discounted_price": disc_price,
                    "discount_percent": discount_pct,
                    "deal_score":       deal_score,
                    "product_url":      product_url,
                    "affiliate_url":    product_url,
                    "image_url":        image_url,
                    "category":         category,
                    "is_active":        True,
                    "is_pro_exclusive": False,
                    "updated_at":       datetime.utcnow(),
                }

                # Upsert by URL (idempotent)
                result = db.deals.update_one(
                    {"product_url": product_url},
                    {"$set": doc, "$setOnInsert": {"created_at": datetime.utcnow()}},
                    upsert=True,
                )
                if result.upserted_id or result.modified_count:
                    saved += 1

            except Exception as e:
                logger.debug(f"Deal save error: {e}")

        client.close()
        logger.info(f"💾 Saved/updated {saved}/{len(all_deals)} deals to MongoDB")
        return saved

    except Exception as e:
        logger.error(f"DB save failed: {e}")
        return 0


def main():
    parser = argparse.ArgumentParser(description="ShadowMerchant Scraper Pipeline")
    parser.add_argument("--scrapers", nargs="+", choices=list(SCRAPER_MAP.keys()), help="Scrapers to run")
    parser.add_argument("--all", action="store_true", help="Run all scrapers")
    parser.add_argument("--no-save", action="store_true", help="Don't save to DB (dry run)")
    args = parser.parse_args()

    if args.all:
        to_run = list(SCRAPER_MAP.keys())
    elif args.scrapers:
        to_run = args.scrapers
    else:
        to_run = load_targets()

    logger.info(f"🚀 Pipeline starting — scrapers: {to_run}")
    start = datetime.utcnow()

    all_deals = []
    for name in to_run:
        deals = run_scraper(name)
        all_deals.extend(deals)

    logger.info(f"📦 Total deals collected: {len(all_deals)}")

    saved = 0
    if not args.no_save:
        saved = process_and_save(all_deals)
    else:
        logger.info("[DRY RUN] Skipping DB save")
        # Print sample
        for d in all_deals[:5]:
            raw = d if isinstance(d, dict) else d.__dict__
            print(f"  {raw.get('title', '')[:60]} | ₹{raw.get('discounted_price', 0)} | {raw.get('discount_percent', 0)}% off")

    elapsed = (datetime.utcnow() - start).seconds
    logger.info(f"✅ Pipeline complete — {saved} deals saved in {elapsed}s")


if __name__ == "__main__":
    main()
